# Generated by Django 6.0.2 on 2026-02-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-id',)},
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-id'], name='books_book_id_79bdb8_idx'),
        ),
    ]
