# Generated by Django 6.0.2 on 2026-02-11 09:52

import transaction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateTimeField(default=transaction.models.get_default_due_date),
        ),
    ]
